language: php

dist: xenial
os: linux

php:
  - 7.4

services:
  - docker

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --dev --prefer-dist --no-interaction --working-dir=api

before_script:
  - if [ ! -f .env ]; then cp -i .env.example .env; fi
  - docker-compose -f docker-compose-travis-ci.yml run --rm api-php-cli php api/bin/app.php migrations:migrate --no-interaction

script:
  - docker-compose -f docker-compose-travis-ci.yml run --rm api-php-cli api/vendor/bin/phpunit --configuration api/phpunit.xml --coverage-clover api/var/coverage/clover.xml --colors

after_success:
  - docker-compose -f docker-compose-travis-ci.yml run --rm api-php-cli api/vendor/bin/php-coveralls --json_path=api/var/coverage/coveralls-upload.json --coverage_clover=api/var/coverage/clover.xml -v
