version: "3.7"
services:

  gateway:
    image: ${REGISTRY}/slim-vue-demo-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend-nginx
      - api-nginx
      - ws
      - amqp
      - swagger-ui
      - elk

  frontend-nginx:
    image: ${REGISTRY}/slim-vue-demo-frontend-nginx:${IMAGE_TAG}
    restart: always

  api-nginx:
    image: ${REGISTRY}/slim-vue-demo-api-nginx:${IMAGE_TAG}
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "api-nginx"
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/slim-vue-demo-api-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      API_ENV: prod
      API_DEBUG: 0
      API_DB_HOST: ${API_DB_HOST}
      API_DB_USER: ${API_DB_USER}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      API_DB_NAME: ${API_DB_NAME}
      API_MAILER_HOST: ${API_MAILER_HOST}
      API_MAILER_PORT: ${API_MAILER_PORT}
      API_MAILER_USERNAME: ${API_MAILER_USERNAME}
      API_MAILER_PASSWORD: ${API_MAILER_PASSWORD}
      API_MAILER_ENCRYPTION: ${API_MAILER_ENCRYPTION}
      API_MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      API_OAUTH_PUBLIC_KEY_PATH: ${API_OAUTH_PUBLIC_KEY_PATH}
      API_OAUTH_PRIVATE_KEY_PATH: ${API_OAUTH_PRIVATE_KEY_PATH}
      API_OAUTH_ENCRYPTION_KEY: ${API_OAUTH_ENCRYPTION_KEY}
      API_AMQP_HOST: ${API_AMQP_HOST}
      API_AMQP_PORT: ${API_AMQP_PORT}
      API_AMQP_USERNAME: ${API_AMQP_USERNAME}
      API_AMQP_PASSWORD: ${API_AMQP_PASSWORD}
      API_AMQP_VHOST: ${API_AMQP_VHOST}
      FRONTEND_URL: https://${DOMAIN_FRONTEND}
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "api-php-fpm"

  api-queue-consumer:
    image: ${REGISTRY}/slim-vue-demo-api-queue-consumer:${IMAGE_TAG}
    restart: always
    environment:
      API_ENV: prod
      API_DEBUG: 0
      API_DB_HOST: ${API_DB_HOST}
      API_DB_USER: ${API_DB_USER}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      API_DB_NAME: ${API_DB_NAME}
      API_MAILER_HOST: ${API_MAILER_HOST}
      API_MAILER_PORT: ${API_MAILER_PORT}
      API_MAILER_USERNAME: ${API_MAILER_USERNAME}
      API_MAILER_PASSWORD: ${API_MAILER_PASSWORD}
      API_MAILER_ENCRYPTION: ${API_MAILER_ENCRYPTION}
      API_MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      API_OAUTH_PUBLIC_KEY_PATH: ${API_OAUTH_PUBLIC_KEY_PATH}
      API_OAUTH_PRIVATE_KEY_PATH: ${API_OAUTH_PRIVATE_KEY_PATH}
      API_OAUTH_ENCRYPTION_KEY: ${API_OAUTH_ENCRYPTION_KEY}
      API_AMQP_HOST: ${API_AMQP_HOST}
      API_AMQP_PORT: ${API_AMQP_PORT}
      API_AMQP_USERNAME: ${API_AMQP_USERNAME}
      API_AMQP_PASSWORD: ${API_AMQP_PASSWORD}
      API_AMQP_VHOST: ${API_AMQP_VHOST}
      FRONTEND_URL: https://${DOMAIN_FRONTEND}
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "api-queue-consumer"
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && php bin/app.php tasks:process"

  api-php-cli:
    image: ${REGISTRY}/slim-vue-demo-api-php-cli:${IMAGE_TAG}
    environment:
      APP_ENV: prod
      APP_DEBUG: 0
      API_DB_HOST: ${API_DB_HOST}
      API_DB_USER: ${API_DB_USER}
      API_DB_PASSWORD: ${API_DB_PASSWORD}
      API_DB_NAME: ${API_DB_NAME}
      API_MAILER_HOST: ${API_MAILER_HOST}
      API_MAILER_PORT: ${API_MAILER_PORT}
      API_MAILER_USERNAME: ${API_MAILER_USERNAME}
      API_MAILER_PASSWORD: ${API_MAILER_PASSWORD}
      API_MAILER_ENCRYPTION: ${API_MAILER_ENCRYPTION}
      API_MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      API_OAUTH_PUBLIC_KEY_PATH: ${API_OAUTH_PUBLIC_KEY_PATH}
      API_OAUTH_PRIVATE_KEY_PATH: ${API_OAUTH_PRIVATE_KEY_PATH}
      API_OAUTH_ENCRYPTION_KEY: ${API_OAUTH_ENCRYPTION_KEY}
      API_AMQP_HOST: ${API_AMQP_HOST}
      API_AMQP_PORT: ${API_AMQP_PORT}
      API_AMQP_USERNAME: ${API_AMQP_USERNAME}
      API_AMQP_PASSWORD: ${API_AMQP_PASSWORD}
      API_AMQP_VHOST: ${API_AMQP_VHOST}
      FRONTEND_URL: https://${DOMAIN_FRONTEND}

  api-db:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
      POSTGRES_DB: app
      TZ: Europe/Moscow
    volumes:
      - api-postgres:/var/lib/postgresql/data

  ws:
    image: ${REGISTRY}/slim-vue-demo-ws:${IMAGE_TAG}
    environment:
      WS_JWT_PUBLIC_KEY: ${WS_JWT_PUBLIC_KEY}
      WS_AMQP_URI: ${WS_AMQP_URI}
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && /start.sh && npm start"

  amqp:
    image: ${REGISTRY}/slim-vue-demo-amqp:${IMAGE_TAG}
    environment:
      RABBITMQ_ERLANG_COOKIE: ${API_AMQP_COOKIE}
      RABBITMQ_DEFAULT_USER: ${API_AMQP_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${API_AMQP_PASSWORD}
    volumes:
      - amqp:/var/lib/rabbitmq

  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      URL: ${SWAGGER_CONFIG_URL}
    depends_on:
      - api-nginx

  elk:
    image: ${REGISTRY}/slim-vue-demo-elk:${IMAGE_TAG}
    volumes:
      - elk-data:/var/lib/elasticsearch
    environment:
      ES_JAVA_OPTS: ${ELK_ES_JAVA_OPTS}
    ports:
      - "12201:12201/udp"

volumes:
  api-postgres:
  amqp:
  elk-data:
