version: '3'
services:

  api-nginx:
    container_name: api-nginx
    build:
      context: api/docker
      dockerfile: development/nginx/Dockerfile
      args:
        SWAGGER_URL: ${SWAGGER_URL}
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./api:/var/www/api
    ports:
      - "8081:80"
    depends_on:
      - api-php-fpm

  api-php-cli:
    container_name: api-php-cli
    build:
      context: api/docker
      dockerfile: development/php-cli/Dockerfile
    environment:
      - API_ENV=test
      - API_DEBUG=${API_DEBUG}
      - API_DB_HOST=${API_DB_HOST}
      - API_DB_USER=${API_DB_USER}
      - API_DB_PASSWORD=${API_DB_PASSWORD}
      - API_DB_NAME=${API_DB_NAME}
      - API_MAILER_HOST=${API_MAILER_HOST}
      - API_MAILER_PORT=${API_MAILER_PORT}
      - API_MAILER_USERNAME=${API_MAILER_USERNAME}
      - API_MAILER_PASSWORD=${API_MAILER_PASSWORD}
      - API_MAILER_ENCRYPTION=${API_MAILER_ENCRYPTION}
      - API_MAILER_FROM_EMAIL=${API_MAILER_FROM_EMAIL}
      - API_OAUTH_PUBLIC_KEY_PATH=${API_OAUTH_PUBLIC_KEY_PATH}
      - API_OAUTH_PRIVATE_KEY_PATH=${API_OAUTH_PRIVATE_KEY_PATH}
      - API_OAUTH_ENCRYPTION_KEY=${API_OAUTH_ENCRYPTION_KEY}
      - API_AMQP_HOST=${API_AMQP_HOST}
      - API_AMQP_PORT=${API_AMQP_PORT}
      - API_AMQP_USERNAME=${API_AMQP_USERNAME}
      - API_AMQP_PASSWORD=${API_AMQP_PASSWORD}
      - API_AMQP_VHOST=${API_AMQP_VHOST}
      - FRONTEND_URL=${FRONTEND_URL}
      - TZ=Europe/Moscow
    volumes:
      - ./api:/var/www/api
    working_dir: /var/www/api
    tty: true
    depends_on:
      - project-db
      - mailer

  api-php-fpm:
    container_name: api-php-fpm
    build:
      context: api/docker
      dockerfile: development/php-fpm/Dockerfile
    environment:
      - API_ENV=test
      - API_DEBUG=${API_DEBUG}
      - API_DB_HOST=${API_DB_HOST}
      - API_DB_USER=${API_DB_USER}
      - API_DB_PASSWORD=${API_DB_PASSWORD}
      - API_DB_NAME=${API_DB_NAME}
      - API_MAILER_HOST=${API_MAILER_HOST}
      - API_MAILER_PORT=${API_MAILER_PORT}
      - API_MAILER_USERNAME=${API_MAILER_USERNAME}
      - API_MAILER_PASSWORD=${API_MAILER_PASSWORD}
      - API_MAILER_ENCRYPTION=${API_MAILER_ENCRYPTION}
      - API_MAILER_FROM_EMAIL=${API_MAILER_FROM_EMAIL}
      - API_OAUTH_PUBLIC_KEY_PATH=${API_OAUTH_PUBLIC_KEY_PATH}
      - API_OAUTH_PRIVATE_KEY_PATH=${API_OAUTH_PRIVATE_KEY_PATH}
      - API_OAUTH_ENCRYPTION_KEY=${API_OAUTH_ENCRYPTION_KEY}
      - API_AMQP_HOST=${API_AMQP_HOST}
      - API_AMQP_PORT=${API_AMQP_PORT}
      - API_AMQP_USERNAME=${API_AMQP_USERNAME}
      - API_AMQP_PASSWORD=${API_AMQP_PASSWORD}
      - API_AMQP_VHOST=${API_AMQP_VHOST}
      - FRONTEND_URL=${FRONTEND_URL}
      - TZ=Europe/Moscow
    volumes:
      - ./api:/var/www/api
    working_dir: /var/www/api
    depends_on:
      - api-php-cli

  project-db:
    container_name: project-db
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api
      TZ: Europe/Moscow

  frontend-node:
    container_name: frontend-node
    build:
      context: ./frontend/docker/node
      args:
        - YOUR_APP_WEB_HTTP_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/var/www/frontend
    tty: true
    environment:
      # https://cli.vuejs.org/guide/mode-and-env.html#modes
      # development is used by vue-cli-service serve
      - NODE_ENV=development
      # one way for hot reloading ... see above for details
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
      - YOUR_APP_WEB_HTTP_PORT=8080
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - VUE_APP_WS_URL=${VUE_APP_WS_URL}
    command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn serve"

  mailer:
    image: mailhog/mailhog
    restart: unless-stopped
